// ---------------------------
// This file was generated by Nango (v0.69.22)
// You can version this file
// ---------------------------

export type SyncMetadata_slack_demo_slackusers = void

export interface SlackUser {
  id: string;
  name: string;
  real_name?: string | undefined;
  image_72?: string | undefined;
};

export interface ActionInput_slack_demo_sendslackmessage {
  channel: string;
  text: string;
};

export interface ActionOutput_slack_demo_sendslackmessage {
  ok: boolean;
  channel: string;
  ts: string;
};
